/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;

import Objeto.Cuenta;
import Objeto.modeloCancion;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author Home
 */
public final class vista_Cliente extends javax.swing.JFrame {

    public ArrayList listarolas = new ArrayList();
    public int xx = 0;
    public int total = 0;
    public DefaultListModel modeloLista = new DefaultListModel();
    public int index_Carrito = 0;
    public int numCarro = 0;
    public ArrayList Cuenta = new ArrayList();

    /**
     * Creates new form vista_Cliente
     */
    public vista_Cliente() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        main_Cliente logic = new main_Cliente();
        logic.recibirCatalogo();
        logic.convertirMaptoList();
        logic.recibirImagenes();
        listarolas = logic.listaCanciones;
        primeraPortada();
        Carrito.setModel(modeloLista);
        btn_Borrar.setEnabled(false);
    }

    // Agregamos un icono SobreEscribimos el Metodo
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Recursos/Audio_Icon.png"));
        return retValue;
    }

    public void primeraPortada() {
        modeloCancion itemRola = (modeloCancion) listarolas.get(xx);
        ImageIcon img = new ImageIcon("Img_Cliente/" + itemRola.pathimg);
        System.out.println("Imagen Default es " + itemRola.pathimg);
        Label_Portadas.setIcon(img);
        text_Id.setText("  " + itemRola.idcancion);
        text_Nombre.setText("  " + itemRola.nombre);
        text_Artista.setText("  " + itemRola.autor);
        text_Año.setText("  " + itemRola.año);
        text_Precio.setText("    " + itemRola.precio);
        xx++;
    }
    // SobreEscribimos para ponerle imagen al JPanel

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_prev = new javax.swing.JLabel();
        btn_next = new javax.swing.JLabel();
        Label_Portadas = new javax.swing.JLabel();
        label_Total = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        text_Precio = new javax.swing.JTextField();
        text_Id = new javax.swing.JTextField();
        text_Nombre = new javax.swing.JTextField();
        text_Artista = new javax.swing.JTextField();
        text_Año = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Carrito = new javax.swing.JList();
        btn_addCart = new javax.swing.JLabel();
        btn_Borrar = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MusicStore");
        setIconImage(getIconImage());
        setPreferredSize(new java.awt.Dimension(700, 450));
        setResizable(false);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        getContentPane().setLayout(null);

        btn_prev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/prev.png"))); // NOI18N
        btn_prev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_prevMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_prevMouseReleased(evt);
            }
        });
        getContentPane().add(btn_prev);
        btn_prev.setBounds(40, 350, 126, 36);

        btn_next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/next.png"))); // NOI18N
        btn_next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_nextMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_nextMouseReleased(evt);
            }
        });
        getContentPane().add(btn_next);
        btn_next.setBounds(200, 350, 126, 36);

        Label_Portadas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(Label_Portadas);
        Label_Portadas.setBounds(40, 50, 282, 283);

        label_Total.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        label_Total.setForeground(new java.awt.Color(255, 255, 255));
        label_Total.setText("Total :   0  $");
        getContentPane().add(label_Total);
        label_Total.setBounds(410, 220, 230, 26);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(480, 220, 0, 0);

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(360, 80, 70, 26);

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" Artista :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(360, 110, 70, 26);

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" Año :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(380, 140, 50, 26);
        getContentPane().add(text_Precio);
        text_Precio.setBounds(440, 180, 90, 30);
        getContentPane().add(text_Id);
        text_Id.setBounds(440, 50, 60, 30);
        getContentPane().add(text_Nombre);
        text_Nombre.setBounds(440, 80, 230, 30);
        getContentPane().add(text_Artista);
        text_Artista.setBounds(440, 110, 230, 30);
        getContentPane().add(text_Año);
        text_Año.setBounds(440, 140, 230, 30);

        Carrito.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {  };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        Carrito.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                CarritoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(Carrito);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(380, 260, 290, 80);

        btn_addCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/addtocart.png"))); // NOI18N
        btn_addCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_addCartMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_addCartMouseReleased(evt);
            }
        });
        getContentPane().add(btn_addCart);
        btn_addCart.setBounds(540, 180, 126, 36);

        btn_Borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/delete.png"))); // NOI18N
        btn_Borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_BorrarMouseReleased(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_BorrarMousePressed(evt);
            }
        });
        getContentPane().add(btn_Borrar);
        btn_Borrar.setBounds(530, 350, 126, 36);

        jLabel8.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" Precio :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(370, 180, 60, 26);

        jLabel9.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ID Cancion :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(340, 50, 86, 26);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/wood_texture1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 700, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void btn_nextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nextMousePressed
        btn_next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/next-push.png")));
        xx++;
        if (xx >= listarolas.size()) {
            xx = 0;
        }
        System.out.println("Valor de XX = "+xx);
        modeloCancion itemRola = (modeloCancion) listarolas.get(xx);
        ImageIcon img = new ImageIcon("Img_Cliente/" + itemRola.pathimg);
        System.out.println("Imagen Default es " + itemRola.pathimg);
        Label_Portadas.setIcon(img);
        text_Id.setText("  " + itemRola.idcancion);
        text_Nombre.setText("  " + itemRola.nombre);
        text_Artista.setText("  " + itemRola.autor);
        text_Año.setText("  " + itemRola.año);
        text_Precio.setText("     " + itemRola.precio);
    }//GEN-LAST:event_btn_nextMousePressed

    private void btn_nextMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nextMouseReleased
        btn_next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/next.png")));
    }//GEN-LAST:event_btn_nextMouseReleased

    private void btn_prevMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prevMousePressed
        btn_prev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/prev-push.png")));
        xx--;
        if (xx < 0) {
            xx = listarolas.size() -1;
        }
        //Obtenemos la Lista de Canciones y llenamos la info
        System.out.println("Valor de XX = "+xx);
        modeloCancion itemRola = (modeloCancion) listarolas.get(xx);
        ImageIcon img = new ImageIcon("Img_Cliente/" + itemRola.pathimg);
        //System.out.println("Imagen Default es " + itemRola.pathimg);
        Label_Portadas.setIcon(img);
        text_Id.setText("  " + itemRola.idcancion);
        text_Nombre.setText("  " + itemRola.nombre);
        text_Artista.setText("  " + itemRola.autor);
        text_Año.setText("  " + itemRola.año);
        text_Precio.setText("    " + itemRola.precio);
    }//GEN-LAST:event_btn_prevMousePressed

    private void btn_prevMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prevMouseReleased
        btn_prev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/prev.png")));
    }//GEN-LAST:event_btn_prevMouseReleased

    private void btn_addCartMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addCartMousePressed
        btn_addCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/addtocart-push.png")));
        System.out.println("Valor de XX en ADD = "+xx);
        modeloCancion rola_Salida = (modeloCancion) listarolas.get(xx);
        Cuenta cu = new Cuenta(rola_Salida.idcancion, rola_Salida.nombre, rola_Salida.precio);
        System.out.println("El precio del Producto a Agregar es "+ cu.precioSong+" "+cu.nombreSong);
        Cuenta.add(cu);
        System.out.println("Numero de Venta = "+Cuenta.size());
        modeloLista.addElement("   "+rola_Salida.nombre+" -  "+rola_Salida.autor);
        total = total + rola_Salida.precio;
        label_Total.setText("Total a Pagar : "+ total+"  $");
        System.out.println("Numero de Ventas(Agregar) = "+Cuenta.size());
    }//GEN-LAST:event_btn_addCartMousePressed

    private void btn_addCartMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addCartMouseReleased
        btn_addCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/addtocart.png")));
    }//GEN-LAST:event_btn_addCartMouseReleased

    private void btn_BorrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BorrarMousePressed
        btn_Borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/delete-push.png")));
        System.out.println("Valor de Index_Carrito en Borrar "+index_Carrito);
        if (index_Carrito != -1 ) {
            Cuenta operacion = (Cuenta) Cuenta.get(index_Carrito);
            System.out.println("El precio del Producto a Remover es "+ operacion.precioSong+" "+operacion.nombreSong);
            total = total - operacion.precioSong;
            label_Total.setText("Total a Pagar : "+ total+"  $");
            btn_Borrar.setEnabled(false);
            Cuenta.remove(index_Carrito);
            modeloLista.removeElementAt(index_Carrito);
            System.out.println("Numero de Ventas(Borrar) = "+Cuenta.size());
        }else {
            System.out.println("El valor de Index es Negativo");
        }
        btn_Borrar.setEnabled(false);
    }//GEN-LAST:event_btn_BorrarMousePressed

    private void btn_BorrarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BorrarMouseReleased
        btn_Borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/delete.png")));
    }//GEN-LAST:event_btn_BorrarMouseReleased

    private void CarritoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_CarritoValueChanged
        index_Carrito = (Carrito.getSelectedIndex());
        System.out.println("Valor Index_Carrito en Seleccion = "+(index_Carrito));
        btn_Borrar.setEnabled(true);
    }//GEN-LAST:event_CarritoValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                vista_Cliente vista = new vista_Cliente();
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList Carrito;
    private javax.swing.JLabel Label_Portadas;
    private javax.swing.JLabel btn_Borrar;
    private javax.swing.JLabel btn_addCart;
    private javax.swing.JLabel btn_next;
    private javax.swing.JLabel btn_prev;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_Total;
    private javax.swing.JTextField text_Artista;
    private javax.swing.JTextField text_Año;
    private javax.swing.JTextField text_Id;
    private javax.swing.JTextField text_Nombre;
    private javax.swing.JTextField text_Precio;
    // End of variables declaration//GEN-END:variables
}
